### ISSUE TITLE
Identical sequences are placed in different OGs?? 

### ISSUE THREAD

**Issue by aldertzomer** [sanger-pathogens/Roary#188]
Hi
I  used Roary 3.2.7 to find the orthologs in a collection of 650 e.coli isolates (commandline: roary -e --mafft *.gff)  To my surprise identical sequences are placed in different clusters.  (  I have reproduced this error with Roary 3.3.4 in a smaller set of 11 genomes, here only two out of 4000 genes are duplicates, so it appears it may be fixed, however not completely.)

Total genes:    40335 according to summary_statistics
 cat pan_genome_reference.fa |fasta2tab |cut -f 3 |wc -l
40335
 cat pan_genome_reference.fa |fasta2tab |cut -f 3 |sort |uniq |wc -l
38458
This not a few OGs, these are almost 2000 OGs with *identical* nucleotide sequence being split up.  

I see other even weirder errors as well, e.g with ~1700 neisseria genomes:
Total genes:    46351 according to summary_statistics
cat pan_genome_reference.fa |fasta2tab |cut -f 3 |wc -l
158976 (far to high)
cat pan_genome_reference.fa |fasta2tab |cut -f 3 |sort|uniq |wc -l
53305 (triplication of the sequences??? and still more than 46351)

or with 15 or so staphylococcus genomes:
Total genes:    4684 according to summary_statistics
cat mrsa/pan_genome_reference.fa |fasta2tab |cut -f 3 |wc -l
11696 
cat mrsa/pan_genome_reference.fa |fasta2tab |cut -f 3 | sort|uniq |wc -l
7199 (duplicate sequences)
cat mrsa/pan_genome_reference.fa |fasta2tab |cut -f 1 | sort|uniq |wc -l
7202 (duplicate names as well?? the protein names are unique in my genome files) 

In some cases there are duplicate genes in the pan genome reference file, sometimes there are genes with duplicate sequences. The numbers don't add up with the summary statistics file or the gene presence absence matrix. Also, by manually checking I found genes with exactly the same sequence placed in two different clusters in the gene_presence_absence file. 

These are serious errors and I feel some release testing should have been implemented (especially as this is published software).  Although the 3.3.4 release appears to fix some of the issues, it is still not correct. Could you please take if you can reproduce this issue? Here's the 11 genomes set:

http://klif.vet.uu.nl/mrsa/ 
(roary -e --mafft *.gff results in 4683 OGs, with 2 identical sequences as separate OGs)

fasta2tab transforms  fasta file into a tab delimited file. This is just some perl code. 
perl -e '$count=0; $len=0; while(<>) {s/\r?\n//; s/\t/ /g; if (s/^>//) { if ($. != 1) {print "\n"} s/ |$/\t/; $count++; $_ .= "\t";} else {s/ //g; $len += length($_)} print $_;} print "\n"; warn "\nConverted $count FASTA records in $. lines to tabular format\nTotal sequence length: $len\n\n";'

**Comment by andrewjpage** [comment]
Hi,
There was a bug (recently fixed) where if you ran roary repeatedly in the same directory, the pan_genome_reference.fa file would be appended to. This is now fixed and on your test data the number of sequences matches the summary statistics file.

As for duplicate sequences, we split clusters which contain paralogs based on a conserved gene neighbourhood and Roary is working exactly as intended.  Using your data as an example, 4682 clusters are identified, and 4680 are unique. Looking at one of the split duplications (transposase for IS431mec), one sample has 2 copies of a gene (12S05158-1_02635 and 12S05158-1_01700). Roary correctly keeps 12S05158-1_01700 as part of the big cluster since there is supporting evidence from the genes around it, and splits 12S05158-1_02635 into its own cluster. 12S05158-1_02635 is a single gene on a single contig and is flagged as 'Investigate' in the QC column of the gene_presence_absence.csv spreadsheet.  

Any pull requests would be welcomed if you wish to expand on the existing 756 tests.
Regards,
Andrew

**Comment by aldertzomer** [comment]
I was unaware that such an emphasis is placed on genetic context.

So you're saying that even if there is indication of an orthologous relationship (identical sequence), but not enough evidence of the same genetic context (maybe because of an IS element insertion and the resulting contig break in the assembly of Illumina reads), genes still get assigned to a new OG? 

In the case of my coli example, 1500 (!) genes are identical to genes in another OG. I've already seen many examples where a contig break next to a gene causes this separation into two different OGs (see here: http://klif.vet.uu.nl/example.xlsx for an example). Is there a way to or switch of this genetic context feature, or add a flag in the QC that says "potentially belongs to OG such and such". I fear that if I would include genes with a couple mismatches, it would be far more than 1500 genes that have been incorrectly assigned to a new OG and I'd really like to prevent this somewhat unexpected behavior of your tool.

**Comment by andrewjpage** [comment]
Theres an undocumented parameter to turn off the splitting, just pass in
the '-s' flag.  I'll add it to the documentation since it sounds like its
of use.

By default if a cluster contains a paralog, we try and split it. We go back
to the original contig and look at 5 genes on either side of each sequence
to create a finger print. Then we use this to iteratively separate them
out. Its used in other algorithms like PanOCT.

**Comment by aldertzomer** [comment]
Thank you very much, this will help a lot. Especiially with some of my datasets which have a lot of contig breaks due to IS elements.
